server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadata-map:
      instanceId: ${spring.application.name}:${vcap.application.instance_index:${server.port}}
      
  client:
    register-with-eureka: false
    fetch-registry: false
