spring:
  application:
    name: ${vcap.application.name:auto-simulator}
  sleuth:
    sampler:
      percentage: 1      
        
security:
  basic:
    enabled: false    
    
feign:
  hystrix:
    enabled: false           

logging:
  file: /Users/cjohnson/Documents/demo-workspace/auto-simulator.log    

---  
spring:
  profiles: development
  
  rabbitmq:
    host: ${RABBIT_HOST:localhost}    
  