eureka:
  client:
    service-url:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://localhost:8761}/eureka/

# This cloud profile only needed until the eureka config above works or the registry server
# is no longer needed
---
spring:
  profiles: cloud

eureka:
  client:
    service-url:
      defaultZone: http://simulator-registry.cfapps.io/eureka/
---
spring:
  profiles: development

server:
   port: 8080

rabbitmq:
    uri: tiger.cloudamqp.com
    vhost: dzmmizcc
    username: dzmmizcc
#    password: '{cipher}8f7dd2647915a955e36f99e75bf81c616b5ae78845afe9f0cfe10b9eba1c8a82b28072c83c0b43b1104c28c1143910d4653b51439731859cbeb3c18c6ccceec4'
    password: v-tY2b5xjrjqgkC3TJ9rbbHgyKOlZDSM
