radius: 100
make: Ford
state: new
pageNum: 1
pageSize: 10
sortby: distance
view:  basic

dealer:
  service:
    apiKey: wyanxf4hcvq7reh379nb5z67  

eureka:
  client:
    serviceUrl:
      defaultZone: http://${vcap.services.service-registry.credentials.uri:127.0.0.1:8761}/eureka/

---
spring:
  profiles: development
  
server:
   port: 8081
   
   
