server:
  port: 9411

spring:
  application:
    name: ${vcap.application.name:zipkin-server}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
  datasource:
    initialize: true
  sleuth:
    enabled: false    
        

    

      