spring:
  application:
    name: ${vcap.application.name:places-service}
  sleuth:
    hystrix:
      strategy.enabled: false    

security:
  basic:
    enabled: false
    
hystrix:
  command:
    default:    
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            