spring:
  application:
     name: simulatorConfigServer
  cloud:
    config:
      server: 
        git:
          uri:  https://github.com/Pivotal-Field-Engineering/pcf-vehicle-simulator-microservices
          searchPaths: apps/VehicleSimulator/config/src/main/resources
#  profiles:
#     active: native
 
        