spring:
  application:
    name: ${vcap.application.name:dealer-service}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}    
  sleuth:
    sampler:
      percentage: 1    

security:
  basic:
    enabled: false  
       
feign:
  hystrix:
    enabled: false     
            
logging:
  file: /Users/cjohnson/Documents/demo-workspace/dealer-service.log
